### ISSUE TITLE
recent Shadow Dom changes broke scrollbars in editor

### ISSUE THREAD

**Issue by anomaly256** [bmathews/atom-dark-ui-slim#4]
Hi,

Since the Shadow Dom became default, the scrollbars within the editor pane are no longer being styled.  There might be other shadow dom related issues as well, I haven't looked extensively although Deprecation Cop lists several selectors that need to be updated

**Comment by bmathews** [comment]
@anomaly256, it should be fixed now. If you have a chance to verify, that'd be great!

**Comment by anomaly256** [comment]
Looks good, thanks!
